### ISSUE TITLE
include expects an array

### ISSUE THREAD

**Issue by Juntylpromicrochip1** [devcontainers/images#1013]
include expects an array

```
  branches:
   include:
     - master
  paths:
    include:
      - manifests
```

_Originally posted by @msftrubengu in https://github.com/microsoft/winget-pkgs/pull/30346#discussion_r729246360_
